### ISSUE TITLE
When incemtenting after a mdx clear (tm1.cells.clear_with_mdx) it fails

### ISSUE THREAD

**Issue by lieslberry** [cubewise-code/tm1py#1125]
**Describe the bug**
I am getting the below error when clearing out with mdx and then running tm1.cells.write(mdx, cells, increment=True)

Traceback (most recent call last):
  File "C:\Projects\Training\main.py", line 21, in <module>
    tm1.cells.write("FX Daily", cellset_as_dict=cells, increment=True)
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 898, in write
    return self.write_through_cellset(cube_name, cellset_as_dict, dimensions, increment, deactivate_transaction_log,
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 913, in write_through_cellset
    return self.write_values_through_cellset(
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 125, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 99, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 1499, in write_values_through_cellset
    self.update_cellset(cellset_id=cellset_id, values=values, sandbox_name=sandbox_name, **kwargs)
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 56, in wrapper
    return func(self, cellset_id, *args, **kwargs)
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 1520, in update_cellset
    for o, value in enumerate(values):
  File "C:\Python\lib\site-packages\TM1py\Services\CellService.py", line 1497, in <genexpr>
    values = (x + (y or None) for x, y in zip(values, current_values))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**To Reproduce**
This is the code:

from TM1py import TM1Service

with TM1Service(address = "", port=12354, ssl=True, user="admin", password="apple") as tm1:    
cells = {}    
cells["2022-01-01", "AUD", "AUD", "Spot"] = 200    
cells["2022-01-02", "AUD", "AUD", "Spot"] = 300    
mdx = """    
SELECT         {[FX Daily Date].[FX Daily Date].[2022-01-01],        [FX Daily Date].[FX Daily Date].[2022-01-02]} *        {[FX Daily Measure].[FX Daily Measure].[Spot]}    ON COLUMNS ,         {[FX Daily Currency From].[FX Daily Currency From].[AUD]}*        {[FX Daily Currency To].[FX Daily Currency To].[AUD]}    ON ROWS     FROM [FX Daily]     
"""    
tm1.cells.clear_with_mdx("FX Daily", mdx)    
tm1.cells.write("FX Daily", cellset_as_dict=cells, increment=True)

**Expected behavior**
I am expecting that it will run with no error.

**Version**
TM1py 1.11.3
TM1 Server Version: 11.8

**Comment by MariusWirtz** [comment]
this is fixed in latest relase 2.0.3
Please upgrade tm1py

```
pip install tm1py --upgrade
```
