### ISSUE TITLE
TM1 12 MCSP connection example doesn't work

### ISSUE THREAD

**Issue by Wuzardor** [cubewise-code/tm1py#1179]
**Describe the bug**
When trying to connect me with TM1py to a PA MSCP environment with the exemple provided, it doesn't work.

**To Reproduce**
**When try this code:** 
```
from TM1py import TM1Service
from TM1py.Utils.Utils import build_pandas_dataframe_from_cellset

params = {
    "base_url": "https://eu-central-1.planninganalytics.saas.ibm.com/api/mytenant/v0/tm1/mydb/",
    "user": "apikey",
    "password": "myapikey",
    "async_requests_mode": True,
    "ssl": True,
    "verify": True
}
MDX ='mymdxrequest'
with TM1Service(**params) as tm1:
    data = tm1.cubes.cells.execute_mdx(MDX)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df.head)
```

**I get this answer:**

> Traceback (most recent call last):
>   File "c:\Users\Gaetan MAURICE\Desktop\Programmation\TM1py\Test_PAaaS.py", line 73, in <module>
>     with TM1Service(**params) as tm1:
>   File "C:\Python3913\lib\site-packages\TM1py\Services\TM1Service.py", line 53, in __init__
>     self._tm1_rest = RestService(**kwargs)
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 255, in __init__
>     self.connect()
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 270, in connect
>     self._start_session(
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 444, in _start_session
>     response = self.GET(url=url, headers=additional_headers)
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 91, in wrapper
>     response = self.build_response_from_raw_bytes(response.content)
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 658, in build_response_from_raw_bytes
>     urllib_response = RestService.urllib3_response_from_bytes(data)
>   File "C:\Python3913\lib\site-packages\TM1py\Services\RestService.py", line 640, in urllib3_response_from_bytes
>     response.begin()
>   File "C:\Python3913\lib\http\client.py", line 320, in begin
>     version, status, reason = self._read_status()
>   File "C:\Python3913\lib\http\client.py", line 302, in _read_status
>     raise BadStatusLine(line)
> http.client.BadStatusLine: 12.4.1

**Expected behavior**
To resolve this I've look in the TM1py code and espcially the TM1Service ( first error line 53) and its params. And the purpose of the "async_requests_mode" params is for IBM Cloud and not for PAaaS/MCSP so I tried without this params and it worked.
Here is the code: 
```
from TM1py import TM1Service
from TM1py.Utils.Utils import build_pandas_dataframe_from_cellset

params = {
    "base_url": "https://eu-central-1.planninganalytics.saas.ibm.com/api/mytenant/v0/tm1/mydb/",
    "user": "apikey",
    "password": "myapikey",
    "ssl": True,
    "verify": True
}
MDX ='mymdxrequest'
with TM1Service(**params) as tm1:
    data = tm1.cubes.cells.execute_mdx(MDX)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df.head)
```
 I think you should remove the "async_requests_mode" from the TM1 example because it can be disturbing unless you have a good reason to put it and that I don't know.

**Version**
TM1py : 1.11.3
TM1 Server Version: 12.4.1

**Additional context**
I hope to help you and others with this contribution.
Thank you guys for the amazing work you do with TM1py. It's very helpfull and cool.

**Comment by wimgielis** [comment]
Hello,

This one works fine for me:


from TM1py import TM1Service

params = {
    "base_url": "
https://eu-central-1.planninganalytics.saas.ibm.com/api/UO6......E/v0/tm1/SmartCo/
",
    "user": "apikey",
    "password": "azE6dXNyX............Z5ay9JdzRJPTo4UTlR",
    "async_requests_mode": True,
    "ssl": True,
    "verify": True
}

with TM1Service(**params) as tm1:
    with open('testwim.txt', 'a') as f:
        f.write(tm1.server.get_product_version())


Op do 17 okt 2024 om 16:33 schreef Wuzardor ***@***.***>:

**Comment by MariusWirtz** [comment]
`async_requests_mode` should work fine with v12.
I think you just need to upgrade TM1py to 2.0.4 or 2.0.5 (available on GitHub not released to PyPI yet)

It exists because in v11 PAoC, any request that runs longer than 30 seconds times out. 
So, if you have a big MDX query or a long-running TI, TM1py must use this. 

But it's generally considered a good practice to use "invoke & poll" approach in these kinds of situations, so it would make sense to use async requests for v12 IMO

**Comment by MariusWirtz** [comment]
`readme.md` improved with 2dd7554f9935984311ae3078857cd69ed2bfd379
