### ISSUE TITLE
SSL Issue cam passport auth

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#121]
Trying to get the CAM passport auth to work and I am running into SSL issues. I ended up spending a few hours going down a testing and research hole but could not find anything that would help. We are using Python on windows.

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bi-host.company.com', port=443): Max retries exceeded with url: /Cognos/cgi-bin/cognosisapi.dll (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Dev/TM1HelperPy/TM1HelperPy/TestCAM.py", line 18, in <module>
    password=None) as tm1:
  File "C:\Dev\TM1py\TM1py\Services\TM1Service.py", line 12, in __init__
    self._tm1_rest = RESTService(**kwargs)
  File "C:\Dev\TM1py\TM1py\Services\RESTService.py", line 116, in __init__
    decode_b64=self.translate_to_boolean(kwargs.get("decode_b64", False)))
  File "C:\Dev\TM1py\TM1py\Services\RESTService.py", line 197, in _start_session
    gateway)
  File "C:\Dev\TM1py\TM1py\Services\RESTService.py", line 278, in _build_authorization_token
    response = requests.get(gateway, auth=HttpNegotiateAuth())
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bi-host.company.com', port=443): Max retries exceeded with url: /Cognos/cgi-bin/cognosisapi.dll (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
`

**Comment by MariusWirtz** [comment]
Hi @rclapp ,

sorry for the late response and thanks for challenging the new features!

We did all our tests against gateways that use HTTP instead of HTTPS. 
As a workaround for the moment you could do two things.
1. Provide a `ClientCAMURI `that uses HTTP instead of HTTPS. 
2. On the python side you could switch off ssl verification for the request against the CAM gateway: you could change line 278 in the RestService to:
`response = requests.get(gateway, auth=HttpNegotiateAuth(), verify=False)`
I think this should work

We will provide a fix for TM1py so that could you could pass a certificate for the CAM gateway, when instantiating the TM1Service. I will create a seperate issue for this feature.

**Comment by MariusWirtz** [comment]
Fixed with MR #131
