### ISSUE TITLE
CellService' object has no attribute 'delete_cellset

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#149]
**Describe what did you try to do with TM1py**
Hi - I am trying to execute the following lines in the TM1py script you had helped me with but get an error on the highlighted line:
    # Execute MDX Query and get the allocation data from the cube
    allocation_data = tm1.cubes.cells.execute_mdx_rows_and_values(
        mdx=mdx_allocation_assumptions,
        **element_unique_names=False)**

This is the error message:

"D:\Program Files\Python37\python.exe" D:/TM1scripts/scratch_StateTax.py
Traceback (most recent call last):
  File "D:/TM1scripts/scratch_StateTax.py", line 164, in <module>
    element_unique_names=False)
  File "D:\Program Files\Python37\lib\site-packages\TM1py\Services\CellService.py", line 352, in execute_mdx_rows_and_values
    return self.extract_cellset_rows_and_values(cellset_id, element_unique_names, delete_cellset=True)
  File "D:\Program Files\Python37\lib\site-packages\TM1py\Services\CellService.py", line 26, in wrapper
    self.delete_cellset(cellset_id=cellset_id)
AttributeError: 'CellService' object has no attribute 'delete_cellset'

I was initially getting a division by zero error so i grabbed the copy of CellService i had working on my laptop.  Running the same script on my local laptop i am not getting any errors.  I am running python 3.6 on my laptop and the client has 3.7

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. This had been returning the set of allocation data

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by jbeanz23** [comment]
I think i resolved this one myself.
You can close it.  Thanks
