### ISSUE TITLE
tm1py and powerbi getting started ?

### ISSUE THREAD

**Issue by watersnick** [cubewise-code/tm1py#306]
Hi - Tm1py 1.5 looks like a fantastic release, very keen to explore the new features that support PowerBI integration.
Do you have an example that I can use to get started with maybe ?.
KR Nick

**Comment by MariusWirtz** [comment]
Hi @watersnick,

thanks! It's actually pretty straightforward. Here is what you need to do:

- Install PowerBI Desktop

- Create a new report / pbix file

In order to bring data into the report, you have to use python scripts as data sources for PowerBI.
So you have to bring in 
- facts from a cube view / MDX query 
- elements from dimensions

For every dataset that you want to retrieve you have to go through the below steps:

1. Go to `Get data` -> `More...` -> `other` -> `python script`

2. prototype the py script that retrieves the data you need in Jupyter

The two functions that you need are the `execute_mdx` / `execute_view` function to retrieve data from a cube.

```python
with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1:
    data = tm1.power_bi.execute_view(cube_name="Sales", view_name="PowerBI", private=False)
```

|     |   Time | Industry         | Executive      |   Customer |   Business Unit |   Product | State   |   Gross Margin |    Revenue |      COGS |
|----:|-------:|:-----------------|:---------------|-----------:|----------------:|----------:|:--------|---------------:|-----------:|----------:|
|   0 | 201308 | CPG              | Andrew Ma      |      10008 |              49 |        30 | TX      |      -5048.78  |    nan     |   5048.78 |
|   1 | 201308 | CPG              | Andrew Ma      |      10017 |              49 |        30 | NY      |      -5821.12  |    nan     |   5821.12 |
|   2 | 201308 | Energy           | Valery Ushakov |      10035 |              31 |        50 | OH      |     -60384.4   |    nan     |  60384.4  |
|   3 | 201308 | Energy           | Carlos Grilo   |      10026 |              48 |        20 | FL      |     -24880     |    nan     |  24880    |


The `get_member_properties` function retrieves a slice of a dimension.

```python
with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1:

    customers = tm1.power_bi.get_member_properties(
        dimension_name="Customer",
        hierarchy_name="Customer",
        member_selection="{Tm1SubsetAll([Customer])}",
        skip_consolidations=True,
        attributes=["State", "City"],
        skip_parents=False)
```

|     | Customer   | Type    | State   | City                     | level000       |
|----:|:-----------|:--------|:--------|:-------------------------|:---------------|
|   0 | 1023       | Numeric | TX      | Irving                   | Total Customer |
|   1 | 10000      | Numeric | IL      | Chicago                  | Total Customer |
|   2 | 10001      | Numeric | IL      | Westchester              | Total Customer |
|   3 | 10002      | Numeric | TX      | Plano                    | Total Customer |
|   4 | 10003      | Numeric | TX      | Fort Worth               | Total Customer |

3. paste the py script into the editor

![image](https://user-images.githubusercontent.com/15182131/89648415-761a2700-d8bf-11ea-930e-0c7405428c94.png)

4. optional: do type conversions by column or add additional logic in PBI to the datasets. You probably want to convert all numbers to decimal numbers. If you have dates as elements make sure to convert them to the type `Date`.

5. optional: express side calculations on the data set in the data tab

Once you have the facts that you need and the dimensions that you want to use for slicing and dicing, you can take a look at the model. PowerBI should be able to autodetect all relations. 

![image](https://user-images.githubusercontent.com/15182131/89647894-9dbcbf80-d8be-11ea-95cb-0c16632cfcd1.png)

- Now you can use the data sets to build a dashboard

You can press the refresh button in the PowerBI ribbon.

![pbi2](https://user-images.githubusercontent.com/15182131/89424639-55739500-d738-11ea-9067-baf06d8e4da7.gif)

Ideally, you are using TM1py with CAM and SSO. Then you don't have to provide a password and the security for your user applies as it is defined in TM1.

When you are done with the dashboard you can publish it.

**Comment by gmc-sanko** [comment]
@MariusWirtz may i ask you a little bit more exactly if this is really a live data connection, which sends a new request every time a filter is applied, or as usual the data is loaded once at the beginning or via refresh?

**Comment by MariusWirtz** [comment]
@gmc-sanko,
PowerBI has a refresh button in the ribbon. As the name suggests, the data is reloaded every time you press that button.
So in that regard, the python data source behaves like every other data source in PowerBI. 
You can see the refresh happening at the beginning of the gif.

**Comment by MariusWirtz** [comment]
Filtering and aggregations happen inside PowerBI when you click on an element of a chart.

Refreshing a python data source is possible in PowerBI Desktop. 
Once the dashboard is hosted in the PBI cloud a data refresh is not possible, just like that.
A simple manual solution to that limitation can be to refresh the dashboard manually and re-upload it.

**Comment by gmc-sanko** [comment]
@MariusWirtz thank you very much for the quick answer. unfortunately it is not a live data connection in the terms of DirectQuery. Thanks a lot.

**Comment by MariusWirtz** [comment]
Unfortunately, PowerBI supports DirectQueries only for some data sources. The python data source is currently not one of them.

**Comment by watersnick** [comment]
Hi @MariusWirtz - this maybe my ignorance and most probably a PowerBI environmental issue, but when I try to execute the following initialisation code...
**from TM1py import TM1Service
with TM1Service(address="localhost", port=8014, user="admin", password="apple", ssl=False) as tm1:
    data = tm1.power_bi.execute_view(cube_name="Revenue", view_name="Revenue Analysis", private=False)**

I get the following error...
Details: "ADO.NET: Python script error.
C:\USERS\XXXX\ANACONDA3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\USERS\XXXX\ANACONDA3\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\USERS\XXXX\ANACONDA3\python.exe"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

I have been using the samples_for_beginners.ipynb example to ensure that my view is working and connects fine, but in PowerBI Python script editor it doesn't seem to want to play nicely !.
Any ideas on how to troubleshoot this ?.

**Comment by MariusWirtz** [comment]
Hi @watersnick,

this looks like some dependency/compatibility issue.
Try to install plain python (= not anaconda) v3.6 + TM1py + pandas + matplotlib.

**Comment by watersnick** [comment]
Thanks @MariusWirtz you are correct it was a dependency issue - installing a new version of Python 3.8 with the required packages fixed the issue - thanks again your guidance ! #noob

**Comment by Andy-Hofelmeyer** [comment]
Hi,
I would like to retrieve TM1/PA data via Python scripts in Power BI.

Environment:
Power BI Version: 2.82.5858.641 64-bit (June 2020)
Planning Analytics 2.0
TM1py installed
Pandas installed
Matplotlib installed
Succesvol test with check.py from tm1py-samples (Planning Analytics 'Planning Sample' could be reached)

I was running:
![image](https://user-images.githubusercontent.com/69905676/90637890-de0c2e00-e22c-11ea-82ac-395e62e92749.png)

=> There was no error messages, but also no data
![image](https://user-images.githubusercontent.com/69905676/90637995-02680a80-e22d-11ea-8391-4fa66f235db9.png)



Then I was running:
![image](https://user-images.githubusercontent.com/69905676/90638484-ac479700-e22d-11ea-9093-43d3f62efe84.png)

=> Then I got this error message:
![image](https://user-images.githubusercontent.com/69905676/90638559-c4b7b180-e22d-11ea-9798-fd0833825f00.png)

Can someone please help me to create a script to retrieve data from a PA view.

Thanks a lot

**Comment by gmc-sanko** [comment]
try tm1.power_bi.execute_view instead of tm1.cubes.cell.get_view_content

**Comment by Andy-Hofelmeyer** [comment]
Hi gmc-sanko,
you mean in my first try to change tm1.cubes.cells.get_view_content into  tm1.power_bi.execute_view?
Like:
![image](https://user-images.githubusercontent.com/69905676/90639870-989d3000-e22f-11ea-83bd-d3abb3cb2abc.png)


Then I am getting this error message:
![image](https://user-images.githubusercontent.com/69905676/90639930-ae125a00-e22f-11ea-95cc-26d87568d0a5.png)

**Comment by gmc-sanko** [comment]
I think you should update TM1py to v1.5

**Comment by MariusWirtz** [comment]
> I think you should update TM1py to v1.5

Yeah. Run `pip install tm1py --upgrade`

**Comment by Andy-Hofelmeyer** [comment]
YYYEESSSS !!!
After updating TM1py it is working:
![image](https://user-images.githubusercontent.com/69905676/90640615-7bb52c80-e230-11ea-8116-1bbc24b17f9b.png)


Thanks a lot. Really...

**Comment by gmc-sanko** [comment]
great 👍

**Comment by MariusWirtz** [comment]
I would recommend putting measures on columns 😉

Good luck!

**Comment by rajatm1** [comment]
Hi,

I'm getting below error while using tm1 connection via Power BI

Unable to connect

Details: "ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 10, in <module>
    from TM1py.Services import TM1Services
ImportError: cannot import name 'TM1Services'

Please help me on this issue

**Comment by rkvinoth** [comment]
import `TM1Service` not `TM1Services`

```Python
from TM1py.Services import TM1Service
```

**Comment by MariusWirtz** [comment]
The approach is now discussed in more depth on the cubewise code blog:
https://code.cubewise.com/tm1py-help-content/getting-tm1-data-into-power-bi

**Comment by drodcic77** [comment]
Hello All,
I see this is an old thread but I am encountering a similar issue with:
power bi desktop v. 2.114.664.0 installed
python v. 3.10 installed
planning analytics v. 2.0.9.14 installed
tm1py 1.10.2 installed
matplotlib installed
pandas installed


with TM1Service(address="localhost", port=15014, ssl=False, user="admin", password="apple", namespace="AD") as tm1: 
    AgencyLOB = tm1.power_bi.get_member_properties(
        dimension_name="AgencyLOB",
        hierarchy_name="AgencyLOB",
        skip_consolidations=True)
AgencyLOB

![pbi python script error tm1service](https://user-images.githubusercontent.com/128635869/228067432-adff266f-4f5a-4f81-a71f-fe5157d8a623.png)

Unable to connect

We encountered an error while trying to connect. Details: "ADO.NET: Python script error.
<pi>NameError: nam 'TM1Service' is not defined
</pi>"

Any help to resolve this error would be greatly appreciated.

**Comment by drodcic77** [comment]
By adding "from TM1py.Services import TM1Service" to the Power BI script it worked.
