### ISSUE TITLE
execute_mdx error when running mdx only one axis

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#416]
**Describe the bug**
Running execute_mdx on a mdx with only one axis throws an error:
```
Traceback (most recent call last):
  File "C:/TM1py/gng//DEV.py", line 45, in <module>
    skip_rule_derived_cells=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 408, in execute_mdx
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 1412, in extract_cellset
    top=top)
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 169, in build_content_from_cellset_dict
    row_axis, column_axis, title_axis = extract_axes_from_cellset(raw_cellset_as_dict=raw_cellset_as_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 109, in extract_axes_from_cellset
    column_axis = axes[1] if axes[1] and "Tuples" in axes[1] and len(axes[1]["Tuples"]) > 0 else None
IndexError: list index out of range

```

**To Reproduce**
```
with TM1Service(address='localhost', port=12354, user='Admin', password='', ssl=True) as tm1:
    mdx = """
    SELECT {[d1].[e1], [d1].[e2]} * {[d2].[e1]} ON 0 FROM [c1]
    """
    cellset = tm1.cells.execute_mdx(mdx=mdx)

```

**Expected behavior**
Return cellset

**Version**
TM1py [e.g. 1.5.0]
TM1 Server Version: [e.g. 11.8]

**Additional context**

**Comment by MariusWirtz** [comment]
@cubewise-gng 

I think it's solved.
Please upgrade to the branch `issue/416-allow-single-axis-mdx-selection` and check if the issue is addressed. 

You can upgrade with pip like this:
`pip install https://github.com/cubewise-code/tm1py/archive/issue/416-allow-single-axis-mdx-selection.zip --upgrade`
