### ISSUE TITLE
Integrated Login Issue 

### ISSUE THREAD

**Issue by TCucen** [cubewise-code/tm1py#483]
Hi All, 

Having an issue to connect to my model when using IntegratedSecurityMode=5
(I can connect to the model when it is set to 1) 

I have Python 3.8.5 & TM1py 1.6.0

Although I have a windows server I am getting this error with mode =5

 File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 456, in _build_authorization_token_cam
    HttpNegotiateAuth
NameError: name 'HttpNegotiateAuth' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/TCU08/Python Files/unused2.py", line 33, in <module>
    with TM1Service(address='XXXX', port=XXXX, namespace='XX', gateway='XXXXXX', ssl=True) as tm1:
  File "C:\Python\lib\site-packages\TM1py\Services\TM1Service.py", line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 185, in __init__
    self._start_session(
  File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 335, in _start_session
    token = self._build_authorization_token(
  File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 447, in _build_authorization_token
    return RestService._build_authorization_token_cam(user, password, namespace, gateway, verify)
  File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 458, in _build_authorization_token_cam
    raise RuntimeError(
RuntimeError: SSO failed due to missing dependency requests_negotiate_sspi.HttpNegotiateAuth. SSO only supported for Windows

Any ideas ? 

Regards,

**Comment by rkvinoth** [comment]
Looks like you are missing the `requests-negatiate-sspi` library. Install it from command prompt using the below command:

`pip install requests-negotiate-sspi`

**Comment by TCucen** [comment]
sorry to mention that, I have already installed it :

Requirement already satisfied: requests-negotiate-sspi in c:\python\lib\site-packages (0.5.2)

**Comment by MariusWirtz** [comment]
@TCucen are you running python on windows or on Linux?

**Comment by MariusWirtz** [comment]
It is possible that you have two installations of python on the machine? (Like perhaps one anaconda and one python)

Perhaps the script uses a different python interpreter than the pip command that you executed?

**Comment by TCucen** [comment]
@MariusWirtz   
I am running python on Windows , but let me check if I have more than one installation. 

one more issue when I try to import the library with :

**_import requests_negotiate_sspi_** 

I get this: 

Traceback (most recent call last):
  File "c:/Users/TCU08/Python Files/unused2.py", line 10, in <module>
    import requests_negotiate_sspi 
  File "C:\Python\lib\site-packages\requests_negotiate_sspi\__init__.py", line 4, in <module>
    from .requests_negotiate_sspi import HttpNegotiateAuth  # noqa
  File "C:\Python\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 10, in <module>
    import pywintypes
  File "C:\Users\TCU08\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 105, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\TCU08\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 87, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes38.dll)

**Comment by MariusWirtz** [comment]
Judging by the error message (_ImportError: No system module 'pywintypes'_) it could be that pypiwin32 is not installed.
Please check if pypiwin32 is installed:

`pip show pypiwin32`

If not please install it:

`pip install pypiwin32`

**Comment by rkvinoth** [comment]
Use the python executable here to call the script and check `c:\python\`

It could be that you have pointed some other python installation in your env variable.

**Comment by TCucen** [comment]
Thx guys, I think it was because of my messy environment. 

I have done a new clean Anaconda installation on the server and it's working now.
