### ISSUE TITLE
OSError('Tunnel connection failed: 407 Proxy Authentication Required')

### ISSUE THREAD

**Issue by srinivas1703** [cubewise-code/tm1py#531]
Hi Team,

I am getting 407 Proxy Authentication Required while executing the python script.
From last one year i am using TM1py. Suddenly  i am getting this error.
However, Same code is working fine in my local and another windows servers. I am not able to run this in one particular windows server i.e  what i have working with this server from last one year.
 Code : 
from TM1py.Services import TM1Service
tm1=TM1Service(address='xx.xxx.xxx.xx',port=12354,user='TM1User',password='April@10th',ssl=True,namespace='ActiveDirectory')
print(tm1)
Versions:
TM1py : 1.5.0
Python : 3.7.2
PA : 2.0.7

Error:
Traceback (most recent call last):
  File "E:\Test.py", line 19, in <module>
    tm1=TM1Service(address='xx.xxx.xxx.xx',port=12354,user='TM1User',password='April@10th',ssl=True,namespace='ActiveDirectory')
  File "E:\Python37\lib\site-packages\TM1py\Services\TM1Service.py", line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "E:\Python37\lib\site-packages\TM1py\Services\RestService.py", line 196, in __init__
    impersonate=kwargs.get("impersonate", None))
  File "E:\Python37\lib\site-packages\TM1py\Services\RestService.py", line 349, in _start_session
    response = self.GET(url=url, headers=additional_headers)
  File "E:\Python37\lib\site-packages\TM1py\Services\RestService.py", line 50, in wrapper
    response = func(self, url, data, **kwargs)
  File "E:\Python37\lib\site-packages\TM1py\Services\RestService.py", line 239, in GET
    timeout=timeout if timeout else self._timeout)
  File "E:\Python37\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "E:\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='xx.xxx.xxx.xx', port=12354): Max retries exceeded with url: /api/v1/Configuration/ProductVersion/$value (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

2. I had updated python and TM1py with 3.9.4 and 1.6.2 versions.
 After that i am getting the following error. ValueError: check_hostname requires server_hostname
Traceback (most recent call last):
  File "E:\Test.py", line 12, in <module>
    tm1=TM1Service(address='xx.xxx.xxx.xx',port=12354,user='TM1User',password='April@10th',ssl=True,namespace='ActiveDirectory')
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\TM1py\Services\TM1Service.py", line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\TM1py\Services\RestService.py", line 185, in __init__
    self._start_session(
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\TM1py\Services\RestService.py", line 349, in _start_session
    response = self.GET(url=url, headers=additional_headers)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\TM1py\Services\RestService.py", line 50, in wrapper
    response = func(self, url, data, **kwargs)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\TM1py\Services\RestService.py", line 234, in GET
    return self._s.get(
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\TM1User\AppData\Roaming\Python\Python39\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Program Files\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

Thanks & Regards,
Srinivas.

**Comment by rkvinoth** [comment]
Are you able to access that server through your client's VPN?

**Comment by srinivas1703** [comment]
Hi rkvinoth,

Yes. Within the server we are not able to run. from out of the server , from local or any other servers also i am able to run this code.


Thanks & Regards,
Srinivas.

**Comment by rkvinoth** [comment]
Its hard to replicate this kind of error, but try checking:

https://github.com/psf/requests/issues?q=Tunnel+connection+failed%3A+407+Proxy+Authentication+Required
