### ISSUE TITLE
KeyError on power_bi.get_member_properties with hierarchy

### ISSUE THREAD

**Issue by casolutions2** [cubewise-code/tm1py#552]
**Describe` what did you try to do with TM1py**
Pull a hierarchy into PowerBI as per the example here https://code.cubewise.com/tm1py-help-content/getting-tm1-data-into-power-bi

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. List of members in the Business Line hierarchy of the CostCentre dimension
2. Code below returns KeyError: 'CostCentre'
```
import configparser
import os

from TM1py import TM1Service
config = configparser.ConfigParser()
directory = os.path.dirname(os.path.abspath(__file__))
os.chdir(directory)
config.read('../config.ini')

with TM1Service(**config["tm1BCProdsrv01"]) as tm1:
    print(tm1.server.get_product_version())
    business_line=tm1.power_bi.get_member_properties(
        dimension_name="CostCentre"
        , hierarchy_name="Business Line"
        , member_selection="Tm1DrillDownMember({[CostCentre].[Business Line].[All Business Line]},All, Recursive)"
        # , skip_consolidations=False
        , attributes=["Code Caption", "Business Line"]
        # , parent_attribute="Business Line"
        # , skip_parents=False
    )
    print(business_line)

````

**Version**
- TM1py 1.6.2
- TM1 Server Version: 11.8.00500.12 on-cloud

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by jrobinsonAG** [comment]
Is you member selection correct? i.e.[ All business Line**s**]?

**Comment by casolutions2** [comment]
Hi Josh, yes this is correct.  I am able to pull in the members using vanilla REST with the following
`Dimensions('CostCentre')/Hierarchies('Business Line')/Members?$select=Name&$expand=Element($select=Name,Type,Attributes)`
But then I get some miscellaneous consolidations that I do not need in Power BI. 
Here is a screenshot of my Hierarchy...
![Screenshot from 2021-06-22 08-23-16](https://user-images.githubusercontent.com/33277778/122835134-2e638900-d333-11eb-9021-ed10798aa379.png)

**Comment by jrobinsonAG** [comment]
Are you able to provide the traceback? This should pinpoint where the exception is being raised.  Ie this is where I was able to replicate the KeyError by misspelling the member selection, thinking this might have been the issues.

Traceback (most recent call last):
  File "c:\Users\username\Envs\tm1py_dev\power_bi.py", line 13, in <module>
    business_line=tm1.power_bi.get_member_properties(
  File "c:\users\username\envs\tm1py_dev\src\tm1py\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\username\envs\tm1py_dev\src\tm1py\TM1py\Services\PowerBiService.py", line 146, in get_member_properties    
    return pd.merge(df, df_data, on=dimension_name).drop_duplicates()
  File "C:\Users\username\Envs\tm1py_dev\lib\site-packages\pandas\core\reshape\merge.py", line 74, in merge
    op = _MergeOperation(
  File "C:\Users\username\Envs\tm1py_dev\lib\site-packages\pandas\core\reshape\merge.py", line 668, in __init__
    ) = self._get_merge_keys()
  File "C:\Users\username\Envs\tm1py_dev\lib\site-packages\pandas\core\reshape\merge.py", line 1033, in _get_merge_keys     
    right_keys.append(right._get_label_or_level_values(rk))
  File "C:\Users\username\Envs\tm1py_dev\lib\site-packages\pandas\core\generic.py", line 1684, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Cost Centre'

**Comment by casolutions2** [comment]
Yes, here it is.  Looks similar to yours.
```
PS H:\Projects\TM1\TM1Py> & C:/Users/Craig.Sawers/AppData/Local/Programs/Python/Python39/python.exe h:/Projects/TM1/TM1Py/TestScripts/PowerBI.py
Traceback (most recent call last):
  File "h:\Projects\TM1\TM1Py\TestScripts\PowerBI.py", line 12, in <module>
    business_line=tm1.power_bi.get_member_properties(
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\PowerBiService.py", line 146, in get_member_properties
    return pd.merge(df, df_data, on=dimension_name).drop_duplicates()
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 74, in merge
    op = _MergeOperation(
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 668, in __init__
    ) = self._get_merge_keys()
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 1033, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 1684, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'CostCentre'
PS H:\Projects\TM1\TM1Py>
```
Please note that the attributes Code Caption and Business Line are empty for some elements.  Could this be an issue?
Thanks, 
Craig.

**Comment by jrobinsonAG** [comment]
Ok, so the Dataframe that is returned does not have the Dimension name in it, it has the Hierarchy Name. Then the dataframe merge operation is passed the Dimension Name. 

![image](https://user-images.githubusercontent.com/65372770/122842097-00387600-d340-11eb-8c44-37c5a30f80da.png)

**Comment by jrobinsonAG** [comment]
#553 created to resolve the issue.

**Comment by casolutions2** [comment]
Hi Josh, I added these 2 lines to my local copy but I am still getting the same error.  

 ```
# override hierarchy name
 df_data.rename(columns={0:dimension_name})
```

**Comment by jrobinsonAG** [comment]
Just to confirm, you made a change to "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\PowerBiService.py" from the traceback above?

**Comment by jrobinsonAG** [comment]
I've made another commit to make the rename operation more robust. Also tested with various options enabled in main function to ensure default, and member selection, and selected, or no properties passed.

**Comment by casolutions2** [comment]
Yes I did, I also included a Print statement just to ensure I was using the right file and the change 'stuck' and the print statement executed.
code:
```
mdx = f"""
        {mdx_with_block}
        SELECT
        {{ {member_selection} }} ON ROWS,
        {{ {column_selection} }} ON COLUMNS
        FROM [{self.elements.ELEMENT_ATTRIBUTES_PREFIX + dimension_name}]  
        """

        df_data = self.execute_mdx(mdx)

        # override hierarchy name
        df_data.rename(columns={0:dimension_name})
        print("rename columns!!")

        # shift levels to right hand side
        if not skip_parents:
```
and output:```

PS H:\Projects\TM1\TM1Py> & C:/Users/Craig.Sawers/AppData/Local/Programs/Python/Python39/python.exe h:/Projects/TM1/TM1Py/TestScripts/PowerBI.py
rename columns!!
Traceback (most recent call last):
  File "h:\Projects\TM1\TM1Py\TestScripts\PowerBI.py", line 12, in <module>
    business_line=tm1.power_bi.get_member_properties(
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Utils\Utils.py", line 52, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\PowerBiService.py", line 150, in get_member_properties
    return pd.merge(df, df_data, on=dimension_name).drop_duplicates()
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 74, in merge
    op = _MergeOperation(
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 668, in __init__
    ) = self._get_merge_keys()
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\reshape\merge.py", line 1033, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "C:\Users\Craig.Sawers\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 1684, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'CostCentre'
PS H:\Projects\TM1\TM1Py> 
```

**Comment by MariusWirtz** [comment]
Hi @casolutions2,

I would like to reproduce this situation. 
Can you post a zip file that includes the cube (.cub), the dimensions (.dim), and the element attributes (.cub + .dim) of the dimensions?

If data is sensitive can post a simplified reproduction of your situation?

**Comment by casolutions2** [comment]
[region.zip](https://github.com/cubewise-code/tm1py/files/6704476/region.zip)
I have tried this code with a few of my dimension hierarchies (including the Leaves hierarchy) and they all come back with the same error.  I have attached a simple dimension with 2 alternate hierarchies, RDNSPackage and Leaves.  Trying the code with either alternate hierarchy in hierarchy_name= resulted in KeyError: 'Region'

Thanks

**Comment by MariusWirtz** [comment]
Hi @casolutions2,

sorry for the late reply. I can't reproduce the error. Below code works for me on your data

``` python
from TM1py import TM1Service

with TM1Service(address='', port=12297, ssl=True, user='admin', password='apple') as tm1:
    print(tm1.server.get_product_version())

    regions = tm1.power_bi.get_member_properties(
        dimension_name="Region",
        hierarchy_name="RDNSPackage",
        member_selection="Tm1DrillDownMember({[Region].[RDNSPackage].[All Consolidations]},All, Recursive)",
        attributes=["Country Code", "Currency"])
    print(regions)

```
