### ISSUE TITLE
Create a temporary TM1 model

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/tm1py#629]
**Describe what did you try to do with TM1py**
I am trying to create a temporary TM1 model, on my laptop (name is AEX199). 2 TM1 models are already running successfully (not through REST API, they are SelfRegistered).

**Describe what's not working the way you expect**
The tm1py code throws an error:

Traceback (most recent call last):
  File "d:/OneDrive/OneDrive - Aexis NV/Wim/TM1/Programs/Python/My scripts/019/Create new TM1 model.py", line 25, in <module>
    new_server = create_server_on_adminhost( adminhost="localhost", server_as_dict=server_as_dict )
  File "C:\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 113, in create_server_on_adminhost
    response.raise_for_status()
  File "C:\Python\Python38\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:5895/api/v1/Servers

However, if I copy the URL and paste in Postman, I successfully retrieve the 2 running TM1 models.

**Version**
- TM1py 1.8
- TM1 Server Version: 2.0.9.10

`from TM1py.Services import TM1Service
from TM1py.Utils import create_server_on_adminhost

server_as_dict = {
"Name":"TEMPORARY",
"IPAddress":"10.59.106.245",
"IPv6Address":None,
"PortNumber":89787,
"UsingSSL": False,
"ClientMessagePortNumber":61098,
"HTTPPortNumber":8050,
"ClientExportSSLSvrCert":False,
"ClientExportSSLSvrKeyID":None,
"AcceptingClients":True
}

new_server = create_server_on_adminhost( adminhost='AEX199', server_as_dict=server_as_dict )`

**Comment by wimgielis** [comment]
I also used localhost instead of AEX199.
The IP address was returned by Postman when I retrieved the 2 existing
servers (the output gives that information).

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op do 14 okt. 2021 om 22:43 schreef Wim Gielis ***@***.***>:
