### ISSUE TITLE
SelfRegistered

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/tm1py#631]
**Describe the bug**
Is SelfRegistered something recent ? Code that works on the laptop does not work for a different TM1 admin host.

**To Reproduce**
On my laptop, I can use "get_all_servers_from_adminhost" without problem. The URL http://localhost:5895/api/v1/Servers (correctly) gives me 2 models, where SelfRegistered = True. The same code connecting to a customer environment gives an error on SelfRegistered. The URL http://localhost:5895/api/v1/Servers (correctly) gives me 4 models, where SelfRegistered is not mentioned in the JSON output.

**Expected behavior**
Be able to get all TM1 models on an admin host

**Version**
TM1py 1.8
TM1 Server Version: 11.8 (own laptop), 11.4 (customer on premise)

**Additional context**
Traceback (most recent call last):
  File "d:/.../test.py", line 17, in <module>
    inspect_users()
  File "d:/.../test.py", line 11, in inspect_users
    tm1_instances_on_server = get_all_servers_from_adminhost(ADDRESS, None, False)
  File "C:\Python\Python38\lib\site-packages\TM1py\Utils\Utils.py", line 81, in get_all_servers_from_adminhost
    server = Server(server_as_dict)
  File "C:\Python\Python38\lib\site-packages\TM1py\Objects\Server.py", line 21, in __init__
    self.self_registered = server_as_dict['SelfRegistered']
KeyError: 'SelfRegistered'

**Comment by wimgielis** [comment]
Thanks. I see that the server version 11.4 dates back to October 2018. That
will probably explain it.

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op wo 20 okt. 2021 om 20:07 schreef Ryan Clapp ***@***.***>:
