### ISSUE TITLE
Chores list doesn't work !  :-(

### ISSUE THREAD

**Issue by turinaa** [cubewise-code/TM1py#67]
Hi guys,

I'm big fan of TM1py !...

... and I need i little help.

I'm create a python script to list all my objects on TM1 server. 
The cubes and dimension works fine but the chores list doesn't.

My chores.py

```python

#Open connection with TM1
with TM1Service(address=address, port=port, user=user, password=password, namespace=namespace, ssl=ssl) as tm1:
    server_name = tm1.server.get_server_name()
    version = tm1.version

    #Write output file
    with open("TM1_Summary{}.txt".format(server_name),"w+") as file:

        #Server name
        file.write("# Server Name: {a}\n".format(a=server_name) )
        file.write("# version: {a}\n".format(a=version) )
        
        #CHORES
        chores = tm1.chores.get_all_names()
        for chore in chores:
            file.write("\nCHORE:{}\n".format(chore))
```

When I try to run the error is show:

```
Traceback (most recent call last):
  File "chores.py", line 33, in <module>
    chores = tm1.chores.get_all_names()
  File "C:\Users\my_User\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\ChoreService.py", line 69, in get_all_names
    response = self._rest.GET(request)
  File "C:\Users\my_User\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 30, in wrapper
    self.verify_response(response=response)
  File "C:\Users\my_User\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 214, in verify_response
    raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason)
TM1py.Exceptions.Exceptions.TM1pyException: Text: {"error":{"code":"","message":"'Chores' resource can not be resolved on type 'EntityContainer'."}} Status Code: 404 Reason: Not Found
```
My output( TM1_Summary.txt)

```
# Server Name: myserver
# version: 10.2.20000.50183
```

Thank you in advance and congratulations by the awesome library.
The TM1 looks like much more funny with that...

**Comment by MariusWirtz** [comment]
Hi,

you get this Error because your TM1 Server is running a very old version.
After you upgrade to TM1 10.2.2 FP 7 or TM1 11 it will work.

**Comment by turinaa** [comment]
Nice one. Thanks
