### ISSUE TITLE
cells get_value does not work with single hierarchy reference

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#680]
**Describe the bug**
Using cells get_value with a single hierarchy reference throws a TM1 exception due to the parsing logic not working properly.

**To Reproduce**

```
scenarioBaseName = tm1.elements.get_attribute_of_elements(dimName, hierName, 'Base Scenario', ['Planning vs Planning 2'])
print(scenarioBaseName)
```
returns

`{'Planning vs Planning 2': 'Planning 2'}`

```
scenarioBaseName2 = tm1.cells.get_value('}ElementAttributes_Scenario', f'{hierName}::Planning vs Planning 2, Base Scenario')
print(scenarioBaseName2)
```

raises

```
Traceback (most recent call last):
  File "/Users/rdclapp/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch_7.py", line 17, in <module>
    scenarioBaseName2 = tm1.cells.get_value('}ElementAttributes_Scenario', f'{hierName}::Planning vs Planning 2, Base Scenario')
  File "/Users/rdclapp/workspaces/public git/TM1py/TM1py/Services/CellService.py", line 169, in get_value
    cellset = dict(self.execute_mdx(mdx=mdx, sandbox_name=sandbox_name, **kwargs))
  File "/Users/rdclapp/workspaces/public git/TM1py/TM1py/Services/CellService.py", line 834, in execute_mdx
    cellset_id = self.create_cellset(mdx=mdx, sandbox_name=sandbox_name, **kwargs)
  File "/Users/rdclapp/workspaces/public git/TM1py/TM1py/Services/CellService.py", line 2021, in create_cellset
    response = self._rest.POST(url=url, data=json.dumps(data, ensure_ascii=False), **kwargs)
  File "/Users/rdclapp/workspaces/public git/TM1py/TM1py/Services/RestService.py", line 80, in wrapper
    self.verify_response(response=response)
  File "/Users/rdclapp/workspaces/public git/TM1py/TM1py/Services/RestService.py", line 449, in verify_response
    raise TM1pyRestException(response.text,
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"501","message":"\"Scenario Compare::Planning vs Planning 2\" : member not found (rte 81)"}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '116', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

```

**Version**
TM1py [1.8.0]

**Comment by MariusWirtz** [comment]
Thanks for reporting the issue @rclapp 

Feel free to open a PR with a fix if you need something short-term.
Otherwise, I will try to get to it next week.
