### ISSUE TITLE
Problem connecting using windows laptop on company network, ok on mac

### ISSUE THREAD

**Issue by jlobeltest** [cubewise-code/tm1py#917]
Hello,

I'm just installing tm1py and trying to do a simple connection.  I can run the following test on my macbook not on vpn or company locked down windows pc:

from TM1py import TM1Service
 
with TM1Service(
        base_url="https://esnonprod.planning-analytics.cloud.ibm.com/tm1/api/QUBEPROD/",
        user="companysite_tm1_automation",
        namespace="LDAP",
        password="mypassword",
        ssl=True,
        verify=True,
        async_requests_mode=True) as tm1:
    print(tm1.server.get_product_version())

However, when I try to run it on the windows pc, I get these errors.  I have tried changing the site and/or the password, and I get different results.  I can see from tm1login.log that it is connecting.  On macbook, running python3.9.  have tried with both 3.9 and 3.10 on pc.  Any ideas?

Error output
Traceback (most recent call last):
  File "C:\Users\lobelj\Downloads\tm1py-samples-master\tm1py-samples-master\testcon2.py", line 3, in <module>
    with TM1Service(
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\TM1Service.py", line 16, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 226, in __init__
    self.connect()
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 246, in connect
    self._start_session(
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 420, in _start_session
    response = self.GET(url=url, headers=additional_headers)
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 85, in wrapper
    response = self.build_response_from_raw_bytes(response.content)
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 619, in build_response_from_raw_bytes
    urllib_response = RestService.urllib3_response_from_bytes(data)
  File "C:\Users\lobelj\AppData\Local\Programs\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 615, in urllib3_response_from_bytes
    return urllib3.HTTPResponse.from_httplib(response)
AttributeError: type object 'HTTPResponse' has no attribute 'from_httplib'

**Comment by jrobinsonAG** [comment]
What version of urblib3 are you running?

**Comment by MariusWirtz** [comment]
This issue is due to a breaking change in urllib3 https://github.com/urllib3/urllib3/issues/2648

The function `from_httplib` has been removed in the `HTTPResponse` class in urllib3. 
This only affects TM1py when using urllib3 > 2.0 in conjunction with the `async_requests_mode`.

I will provide a fix for this. TM1py can implement the `from_httplib` function that was previously implemented in urllib3.
