### ISSUE TITLE
Having trouble connecting using Check.py

### ISSUE THREAD

**Issue by Rangineni1** [cubewise-code/tm1py#99]
Was following steps on how to connect and while checking connectivity to TM1 using Check.py getting errors.I tried updating within the file with  the credentials and server name but still no luck.

Any help on this is really appreciated.

 File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 177, in _start_sessionresponse = self.GET(request=request)
 File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 32, in wrapper
    self.verify_response(response=response)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 239, in verify_response
    raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason)
TM1py.Exceptions.Exceptions.TM1pyException: Text:  Status Code: 401 Reason: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 22, in <module>
    with TM1Service(address=address, port=port, user=user, password=password, namespace=namespace, ssl=ssl) as tm1:
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\TM1Service.py", line 12, in __init__
    self._tm1_rest = RESTService(**kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 99, in __init__
    self._start_session(**kwargs)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 182, in _start_session
    kwargs['password'] = self.decrypt_password(kwargs['password'])
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\site-packages\TM1py\Services\RESTService.py", line 196, in decrypt_password
    return b64decode(encrypted_password).decode("UTF-8")
  File "C:\Users\User1\AppData\Local\Programs\Python\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by Rangineni1** [comment]
SSL Certificate was the reason. once i updated my certificates on the client machine it worked.
